version: "3.9"
services: 
  jenkins:
    build: jenkins
    ports: 
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-data: /var/jenkins_home
      - jenkins-docker: /certs/client:ro
    environment: 
      DOCKER_CERT_PATH: '/certs/client'
      DOCKER_TLS_VERIFY: 1
  docker-dind:
    build:
      image: docker:dind
      ports:
        - 2376:2376
      volumes:
        jenkins-docker-certs: /certs/client
        jenkins-data: /var/jenkins_home
      environment:
        DOCKER_TLS_CRETDIR: /certs


      
