version: "3.9"
networks:
  jenkins:
services: 
  jenkins:
    networks:
      - jenkins
    build: jenkins 
    ports: 
      - 8080:8080
      - 50000:50000
    volumes:
      - /opt/jenkins/jenkins-data:/var/jenkins_home
      - /opt/jenkins/jenkins-docker-certs:/certs/client:ro
    environment: 
      DOCKER_CERT_PATH: '/certs/client'
      DOCKER_TLS_VERIFY: 1
      DOCKER_HOST: tcp://docker:2376
  docker_dind:
    networks:
      jenkins:
        aliases:
          - docker
    image: docker:dind
    privileged: true
    ports:
      - 2376:2376
    volumes:
      - /opt/jenkins/jenkins-docker-certs:/certs/client
      - /opt/jenkins/jenkins-data:/var/jenkins_home
    environment:
      DOCKER_TLS_CRETDIR: /certs
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1



      
